### ISSUE TITLE
Is halfred supposed to be used along with traverson? 

### ISSUE THREAD

**Issue by pzmudzinski** [basti1302/halfred#18]
I am wondering if `Resource` should be used on top of `traverson` responses.
Let's say root URL returns something like this:
```
{
    myItems: {
        href: "http://localhost:8080/api/data/myItems"
    },
}
```
We want to display `myItems` (which is an array of object) on front-end.
So we could write a helper method which would:

1. fetch "root" API object
2. look for requested resource ("myItems")
3. return array of objects under that resource 

Example implementation: 
```
export const api = traverson
  .from('http://localhost:8080/api/data') // root URL
  .jsonHal();

export function fetchRelation(...args) {
  return api.newRequest()
    .follow(args)
    .getResource().result;
}

export function fetchRelationWithEmbeddedResources(...args) {
  return fetchRelation(...args)
    .then(halfred.parse)
    .then(x => x.allEmbeddedResources());
}
```

Example usage:
`fetchRelationWithEmbeddedResources('myItems')`

(notice I am using `traverson-promise` plugin)

Am I missing something here?

**Comment by basti1302** [comment]
I'm not sure I completely understand your question here. Is there a particular problem, a bug or something?
* What do you expect to happen when using this code? 
* What happens instead?

In general, your example resource (the one containing `myItems`) is not valid HAL (see http://stateless.co/hal_specification.html), the link be in should a property named `_links`. So using`.jsonHal()` will not work as expected. Either make the API comply with the HAL spec or use `.json()` instead of `.jsonHal()`.

**Comment by basti1302** [comment]
Closing this for now, feel free to reopen if you have more questions or issues.

**Comment by pzmudzinski** [comment]
It's not a bug - I was just asking what's the use-case of halfred. I thought it's something to use together with traverson but it seems not. Thanks.

**Comment by basti1302** [comment]
halfred is a library to parse HAL resources. Traverson uses it internally. Of course you can use it to parse HAL resources yourself.
